# Generated by Django 5.2.7 on 2025-10-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
