# Generated by Django 5.2.7 on 2025-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
